[package]
name = "ang"
version = "0.3.0"
authors = ["George Burton <burtonageo@gmail.com>"]
description = "Angular types and common helper methods."
documentation = "https://docs.rs/ang"
homepage = "https://github.com/burtonageo/ang"
repository = "https://github.com/burtonageo/ang"
readme = "README.md"
keywords = ["angle", "geometry", "orientation", "degree", "radian"]
license = "MIT"

[dependencies]
approx = "0.3.1"
num-traits = "0.2.6"

[dev-dependencies]
hamcrest = "0.1.5"
quickcheck = "0.8.1"
